[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/fer/*"
  to = "https://fer-reply-tool.onrender.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/ws/*"
  to = "https://automated-written-submission-tool.onrender.com/:splat"
  status = 200
  force = true
